export const provinceIneCodes = new Map<string, string>([
    ['ALAVA', '01'], ['ARABA', '01'],
    ['ALBACETE', '02'],
    ['ALICANTE', '03'], ['ALACANT', '03'],
    ['ALMERIA', '04'],
    ['AVILA', '05'],
    ['BADAJOZ', '06'],
    ['ISLAS BALEARES', '07'], ['ILLES BALEARS', '07'], ['BALEARS, ILLES', '07'],
    ['BARCELONA', '08'],
    ['BURGOS', '09'],
    ['CACERES', '10'],
    ['CADIZ', '11'],
    ['CASTELLON', '12'], ['CASTELLO', '12'],
    ['CIUDAD REAL', '13'],
    ['CORDOBA', '14'],
    ['LA CORUNA', '15'], ['A CORUNA', '15'], ['CORUNA, A', '15'],
    ['CUENCA', '16'],
    ['GERONA', '17'], ['GIRONA', '17'],
    ['GRANADA', '18'],
    ['GUADALAJARA', '19'],
    ['GUIPUZCOA', '20'], ['GIPUZKOA', '20'],
    ['HUELVA', '21'],
    ['HUESCA', '22'],
    ['JAEN', '23'],
    ['LEON', '24'],
    ['LERIDA', '25'], ['LLEIDA', '25'],
    ['LA RIOJA', '26'], ['RIOJA, LA', '26'],
    ['LUGO', '27'],
    ['MADRID', '28'],
    ['MALAGA', '29'],
    ['MURCIA', '30'],
    ['NAVARRA', '31'],
    ['ORENSE', '32'], ['OURENSE', '32'],
    ['ASTURIAS', '33'],
    ['PALENCIA', '34'],
    ['LAS PALMAS', '35'], ['PALMAS, LAS', '35'],
    ['PONTEVEDRA', '36'],
    ['SALAMANCA', '37'],
    ['SANTA CRUZ DE TENERIFE', '38'], ['S.C. TENERIFE', '38'],
    ['CANTABRIA', '39'],
    ['SEGOVIA', '40'],
    ['SEVILLA', '41'],
    ['SORIA', '42'],
    ['TARRAGONA', '43'],
    ['TERUEL', '44'],
    ['TOLEDO', '45'],
    ['VALENCIA', '46'], ['VALÈNCIA', '46'],
    ['VALLADOLID', '47'],
    ['VIZCAYA', '48'], ['BIZKAIA', '48'],
    ['ZAMORA', '49'],
    ['ZARAGOZA', '50'],
    ['CEUTA', '51'],
    ['MELILLA', '52'],
]);

export function getIneCode(provinceName: string): string | null {
    if (!provinceName) return null;
    const normalized = provinceName.toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    return provinceIneCodes.get(normalized) || null;
}
